require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('../config/db');
const Product = require('../models/Product');

// Real, correctly-matching product photos — sourced from the Pexels API by
// running `node seed/fetchImages.js` once (see that file). This reads the
// resulting map so every product shows its actual correct photo instead of a
// random/mismatched stock image.
const fs = require('fs');
const path = require('path');
let imageMap = {};
try {
  imageMap = JSON.parse(fs.readFileSync(path.join(__dirname, 'imageMap.json'), 'utf-8'));
} catch (e) {
  console.warn('imageMap.json not found — run `node seed/fetchImages.js` first. Using placeholder images for now.');
}
function img(seed) {
  return imageMap[seed] || `https://placehold.co/500x400?text=${encodeURIComponent(seed)}`;
}

const products = [
  // ---------------- LAPTOPS ----------------
  {
    name: 'AcerEdge Aspire 3 Coder',
    category: 'Laptops',
    price: 42999,
    rating: 4.1,
    image: img('aspire3'),
    specs: { cpu: 'AMD Ryzen 5 5500U', ram: '8GB', storage: '512GB SSD', display: '15.6" FHD' },
    tags: ['coding', 'budget', 'student'],
    complementaryCategories: ['Mice', 'Laptop Bags', 'Stands'],
    stock: 40,
    description: 'A reliable budget laptop for programming, web browsing, and office work.',
  },
  {
    name: 'HP Pavilion DevBook 14',
    category: 'Laptops',
    price: 54990,
    rating: 4.3,
    image: img('pavilion14'),
    specs: { cpu: 'Intel Core i5-1235U', ram: '16GB', storage: '512GB SSD', display: '14" FHD IPS' },
    tags: ['coding', 'productivity'],
    complementaryCategories: ['Mice', 'Laptop Bags', 'Stands', 'Keyboards'],
    stock: 35,
    description: 'Great balance of performance and portability for developers on the move.',
  },
  {
    name: 'Lenovo IdeaPad Slim Code 5',
    category: 'Laptops',
    price: 58990,
    rating: 4.4,
    image: img('ideapad5'),
    specs: { cpu: 'Intel Core i5-1335U', ram: '16GB', storage: '512GB SSD', display: '15.6" FHD IPS' },
    tags: ['coding', 'multitasking'],
    complementaryCategories: ['Mice', 'Laptop Bags', 'Stands'],
    stock: 30,
    description: 'Excellent for multitasking between IDEs, browsers, and Docker containers.',
  },
  {
    name: 'ASUS Vivobook Pro Dev',
    category: 'Laptops',
    price: 61990,
    rating: 4.5,
    image: img('vivobookpro'),
    specs: { cpu: 'Intel Core i7-1355U', ram: '16GB', storage: '1TB SSD', display: '15.6" OLED' },
    tags: ['coding', 'premium', 'oled'],
    complementaryCategories: ['Mice', 'Laptop Bags', 'Stands', 'Monitors'],
    stock: 20,
    description: 'A stunning OLED display and fast i7 chip make this ideal for serious dev work.',
  },
  {
    name: 'Dell Inspiron Code Runner 15',
    category: 'Laptops',
    price: 47990,
    rating: 4.0,
    image: img('inspiron15'),
    specs: { cpu: 'Intel Core i5-1235U', ram: '8GB', storage: '512GB SSD', display: '15.6" FHD' },
    tags: ['coding', 'budget'],
    complementaryCategories: ['Mice', 'Laptop Bags'],
    stock: 45,
    description: 'Dependable everyday laptop for coding bootcamps and college coursework.',
  },
  {
    name: 'MSI Katana Gaming 15',
    category: 'Laptops',
    price: 74990,
    rating: 4.5,
    image: img('katana15'),
    specs: { cpu: 'Intel Core i7-13620H', gpu: 'RTX 4060 8GB', ram: '16GB', storage: '1TB SSD', display: '15.6" 144Hz' },
    tags: ['gaming', 'premium'],
    complementaryCategories: ['Mice', 'Headphones', 'Keyboards', 'Laptop Bags'],
    stock: 15,
    description: 'A powerful RTX-powered gaming laptop with a buttery-smooth 144Hz display.',
  },
  {
    name: 'ASUS TUF Gaming F15',
    category: 'Laptops',
    price: 68990,
    rating: 4.4,
    image: img('tufF15'),
    specs: { cpu: 'Intel Core i5-13450HX', gpu: 'RTX 4050 6GB', ram: '16GB', storage: '512GB SSD', display: '15.6" 144Hz' },
    tags: ['gaming', 'durable'],
    complementaryCategories: ['Mice', 'Headphones', 'Keyboards'],
    stock: 18,
    description: 'Military-grade durability meets solid 1080p gaming performance.',
  },
  {
    name: 'Lenovo LOQ Gaming 15',
    category: 'Laptops',
    price: 71990,
    rating: 4.3,
    image: img('loq15'),
    specs: { cpu: 'AMD Ryzen 7 7840HS', gpu: 'RTX 4060 8GB', ram: '16GB', storage: '512GB SSD', display: '15.6" 144Hz' },
    tags: ['gaming'],
    complementaryCategories: ['Mice', 'Headphones', 'Keyboards'],
    stock: 12,
    description: 'Strong Ryzen + RTX 4060 combo tuned for modern AAA titles.',
  },
  {
    name: 'Apple MacBook Air M2',
    category: 'Laptops',
    price: 99990,
    rating: 4.8,
    image: img('macbookairm2'),
    specs: { cpu: 'Apple M2', ram: '8GB', storage: '256GB SSD', display: '13.6" Liquid Retina' },
    tags: ['premium', 'coding', 'design'],
    complementaryCategories: ['Mice', 'Laptop Bags', 'Stands'],
    stock: 10,
    description: 'Fanless, silent, and extremely efficient - a favorite for developers and designers.',
  },
  {
    name: 'HP Spectre Business Ultra',
    category: 'Laptops',
    price: 87990,
    rating: 4.6,
    image: img('spectrebiz'),
    specs: { cpu: 'Intel Core i7-1355U', ram: '16GB', storage: '1TB SSD', display: '13.5" 3K2K Touch' },
    tags: ['premium', 'business'],
    complementaryCategories: ['Mice', 'Laptop Bags', 'Stands'],
    stock: 8,
    description: 'A premium convertible built for executives and frequent travelers.',
  },

  // ---------------- SMARTPHONES ----------------
  {
    name: 'Samsung Galaxy M35 5G',
    category: 'Smartphones',
    price: 18999,
    rating: 4.2,
    image: img('galaxym35'),
    specs: { ram: '8GB', storage: '128GB', display: '6.6" AMOLED 120Hz', battery: '6000mAh' },
    tags: ['budget', '5g'],
    complementaryCategories: [],
    stock: 60,
    description: 'A well-rounded 5G phone with a huge battery and AMOLED display.',
  },
  {
    name: 'Redmi Note 13 Pro',
    category: 'Smartphones',
    price: 24999,
    rating: 4.3,
    image: img('redminote13'),
    specs: { ram: '8GB', storage: '256GB', display: '6.67" AMOLED 120Hz', camera: '200MP' },
    tags: ['camera', 'midrange'],
    complementaryCategories: [],
    stock: 55,
    description: 'A 200MP camera flagship-killer at a midrange price point.',
  },
  {
    name: 'Realme Narzo Speed Pro',
    category: 'Smartphones',
    price: 16999,
    rating: 4.0,
    image: img('narzospeed'),
    specs: { ram: '6GB', storage: '128GB', display: '6.6" IPS 120Hz' },
    tags: ['budget'],
    complementaryCategories: [],
    stock: 50,
    description: 'Fast performance for gaming and everyday tasks on a budget.',
  },
  {
    name: 'OnePlus Nord 4',
    category: 'Smartphones',
    price: 29999,
    rating: 4.5,
    image: img('nord4'),
    specs: { ram: '8GB', storage: '256GB', display: '6.74" AMOLED 120Hz', cpu: 'Snapdragon 7+ Gen 3' },
    tags: ['midrange', 'performance'],
    complementaryCategories: [],
    stock: 40,
    description: 'Metal unibody design with flagship-grade Snapdragon performance.',
  },
  {
    name: 'Apple iPhone 14',
    category: 'Smartphones',
    price: 59990,
    rating: 4.7,
    image: img('iphone14'),
    specs: { ram: '6GB', storage: '128GB', display: '6.1" Super Retina XDR', cpu: 'A15 Bionic' },
    tags: ['premium', 'ios'],
    complementaryCategories: [],
    stock: 20,
    description: 'Reliable performance, excellent cameras, and years of iOS updates.',
  },
  {
    name: 'Samsung Galaxy S23 FE',
    category: 'Smartphones',
    price: 49999,
    rating: 4.5,
    image: img('s23fe'),
    specs: { ram: '8GB', storage: '256GB', display: '6.4" AMOLED 120Hz', cpu: 'Snapdragon 8 Gen 1' },
    tags: ['premium', 'camera'],
    complementaryCategories: [],
    stock: 25,
    description: 'Flagship experience distilled into a more affordable package.',
  },

  // ---------------- HEADPHONES ----------------
  {
    name: 'boAt Rockerz 450',
    category: 'Headphones',
    price: 1299,
    rating: 4.1,
    image: img('rockerz450'),
    specs: { type: 'On-ear', battery: '15 hours', connectivity: 'Bluetooth 5.0' },
    tags: ['budget', 'wireless'],
    complementaryCategories: [],
    stock: 100,
    description: 'Affordable wireless headphones with punchy bass for everyday listening.',
  },
  {
    name: 'JBL Tune 770NC',
    category: 'Headphones',
    price: 4999,
    rating: 4.4,
    image: img('jbl770nc'),
    specs: { type: 'Over-ear', battery: '70 hours', anc: true, connectivity: 'Bluetooth 5.3' },
    tags: ['anc', 'wireless', 'gaming'],
    complementaryCategories: [],
    stock: 60,
    description: 'Active noise cancellation with a massive 70-hour battery life.',
  },
  {
    name: 'Sony WH-CH720N',
    category: 'Headphones',
    price: 8990,
    rating: 4.5,
    image: img('sonywhch720'),
    specs: { type: 'Over-ear', battery: '35 hours', anc: true, connectivity: 'Bluetooth 5.2' },
    tags: ['anc', 'premium'],
    complementaryCategories: [],
    stock: 30,
    description: 'Lightweight, comfortable ANC headphones tuned for long listening sessions.',
  },
  {
    name: 'HyperX Cloud Stinger 2 (Gaming)',
    category: 'Headphones',
    price: 3499,
    rating: 4.5,
    image: img('cloudstinger2'),
    specs: { type: 'Over-ear', mic: 'Detachable', connectivity: 'Wired 3.5mm' },
    tags: ['gaming'],
    complementaryCategories: [],
    stock: 40,
    description: 'Comfortable gaming headset with clear directional audio cues.',
  },

  // ---------------- KEYBOARDS ----------------
  {
    name: 'Logitech K380 Multi-Device',
    category: 'Keyboards',
    price: 2999,
    rating: 4.4,
    image: img('k380'),
    specs: { type: 'Wireless', switches: 'Membrane', connectivity: 'Bluetooth' },
    tags: ['compact', 'productivity'],
    complementaryCategories: [],
    stock: 50,
    description: 'Compact wireless keyboard that pairs with up to 3 devices at once.',
  },
  {
    name: 'Redgear Shadow Blade Mechanical',
    category: 'Keyboards',
    price: 2199,
    rating: 4.2,
    image: img('shadowblade'),
    specs: { type: 'Mechanical', switches: 'Blue', backlight: 'RGB' },
    tags: ['gaming', 'budget'],
    complementaryCategories: [],
    stock: 45,
    description: 'Budget mechanical keyboard with satisfying tactile blue switches.',
  },
  {
    name: 'Keychron K8 Wireless Mechanical',
    category: 'Keyboards',
    price: 7499,
    rating: 4.6,
    image: img('keychronk8'),
    specs: { type: 'Mechanical', switches: 'Gateron Brown', connectivity: 'Bluetooth/USB-C' },
    tags: ['coding', 'premium'],
    complementaryCategories: [],
    stock: 25,
    description: 'A developer favorite - hot-swappable switches and multi-device pairing.',
  },

  // ---------------- MICE ----------------
  {
    name: 'Logitech M221 Silent',
    category: 'Mice',
    price: 699,
    rating: 4.3,
    image: img('m221'),
    specs: { type: 'Wireless', dpi: '1000', clickNoise: 'Silent' },
    tags: ['budget', 'coding', 'office'],
    complementaryCategories: [],
    stock: 150,
    description: 'A quiet, reliable wireless mouse perfect for shared workspaces.',
  },
  {
    name: 'HP Wireless Mouse 220',
    category: 'Mice',
    price: 999,
    rating: 4.1,
    image: img('hp220'),
    specs: { type: 'Wireless', dpi: '1600' },
    tags: ['coding', 'budget'],
    complementaryCategories: [],
    stock: 120,
    description: 'A comfortable everyday wireless mouse with a full year battery life.',
  },
  {
    name: 'Logitech MX Anywhere 3S',
    category: 'Mice',
    price: 6495,
    rating: 4.7,
    image: img('mxanywhere3s'),
    specs: { type: 'Wireless', dpi: '8000', scrollWheel: 'MagSpeed' },
    tags: ['premium', 'productivity', 'coding'],
    complementaryCategories: [],
    stock: 30,
    description: 'A precision productivity mouse that works on virtually any surface.',
  },
  {
    name: 'Redgear A-15 Gaming Mouse',
    category: 'Mice',
    price: 799,
    rating: 4.2,
    image: img('a15gaming'),
    specs: { type: 'Wired', dpi: '3200', rgb: true },
    tags: ['gaming', 'budget'],
    complementaryCategories: [],
    stock: 80,
    description: 'RGB gaming mouse with adjustable DPI for fast-paced titles.',
  },
  {
    name: 'Logitech G102 Lightsync Gaming',
    category: 'Mice',
    price: 1395,
    rating: 4.5,
    image: img('g102'),
    specs: { type: 'Wired', dpi: '8000', rgb: true },
    tags: ['gaming'],
    complementaryCategories: [],
    stock: 70,
    description: 'A lightweight, accurate gaming mouse trusted by esports players.',
  },

  // ---------------- MONITORS ----------------
  {
    name: 'Samsung 24" FHD Monitor',
    category: 'Monitors',
    price: 8999,
    rating: 4.3,
    image: img('samsung24fhd'),
    specs: { size: '24"', resolution: '1920x1080', refreshRate: '75Hz' },
    tags: ['budget', 'office'],
    complementaryCategories: [],
    stock: 35,
    description: 'A crisp, affordable second monitor to boost your coding productivity.',
  },
  {
    name: 'LG 27" IPS QHD Monitor',
    category: 'Monitors',
    price: 18999,
    rating: 4.6,
    image: img('lg27qhd'),
    specs: { size: '27"', resolution: '2560x1440', refreshRate: '75Hz' },
    tags: ['coding', 'design', 'premium'],
    complementaryCategories: [],
    stock: 20,
    description: 'Sharp QHD IPS panel with excellent color accuracy for coding and design.',
  },
  {
    name: 'Acer Nitro 27" 165Hz Gaming Monitor',
    category: 'Monitors',
    price: 22999,
    rating: 4.5,
    image: img('acernitro27'),
    specs: { size: '27"', resolution: '1920x1080', refreshRate: '165Hz' },
    tags: ['gaming'],
    complementaryCategories: [],
    stock: 15,
    description: 'High refresh rate gaming monitor for buttery-smooth competitive play.',
  },

  // ---------------- LAPTOP BAGS ----------------
  {
    name: 'American Tourister Laptop Backpack',
    category: 'Laptop Bags',
    price: 1499,
    rating: 4.3,
    image: img('atbackpack'),
    specs: { capacity: '30L', fitsUpTo: '15.6"', material: 'Polyester' },
    tags: ['budget', 'travel'],
    complementaryCategories: [],
    stock: 90,
    description: 'A durable everyday backpack with padded laptop compartment.',
  },
  {
    name: 'HP Renew Business Backpack',
    category: 'Laptop Bags',
    price: 1999,
    rating: 4.4,
    image: img('hprenew'),
    specs: { capacity: '25L', fitsUpTo: '15.6"', material: 'Recycled fabric' },
    tags: ['business', 'eco-friendly'],
    complementaryCategories: [],
    stock: 60,
    description: 'Made from recycled materials, with dedicated laptop and tablet sleeves.',
  },
  {
    name: 'Dell Premier Slim Backpack',
    category: 'Laptop Bags',
    price: 3499,
    rating: 4.6,
    image: img('dellpremier'),
    specs: { capacity: '20L', fitsUpTo: '15"', material: 'Water-resistant nylon' },
    tags: ['premium', 'business'],
    complementaryCategories: [],
    stock: 25,
    description: 'A sleek, professional backpack designed to slim-fit modern laptops.',
  },

  // ---------------- STANDS ----------------
  {
    name: 'Portronics My Buddy Laptop Stand',
    category: 'Stands',
    price: 899,
    rating: 4.2,
    image: img('mybuddy'),
    specs: { material: 'Aluminum', adjustable: true, foldable: true },
    tags: ['budget', 'ergonomic'],
    complementaryCategories: [],
    stock: 100,
    description: 'A foldable, portable stand that improves posture during long coding sessions.',
  },
  {
    name: 'Boya Adjustable Aluminum Laptop Stand',
    category: 'Stands',
    price: 1299,
    rating: 4.4,
    image: img('boyastand'),
    specs: { material: 'Aluminum', adjustable: true, heightRange: '6 levels' },
    tags: ['ergonomic', 'coding'],
    complementaryCategories: [],
    stock: 70,
    description: 'Sturdy 6-level adjustable stand that keeps your laptop cool and elevated.',
  },
  {
    name: 'Zinq Technologies Ergonomic Riser',
    category: 'Stands',
    price: 1799,
    rating: 4.5,
    image: img('zinqriser'),
    specs: { material: 'Aluminum alloy', adjustable: true, cableManagement: true },
    tags: ['premium', 'ergonomic'],
    complementaryCategories: [],
    stock: 30,
    description: 'Premium riser with built-in cable management for a clean desk setup.',
  },
];

async function seed() {
  await connectDB();
  console.log(`Seeding ${products.length} products...`);
  await Product.deleteMany({});
  await Product.insertMany(products);
  console.log('Seed complete.');
  await mongoose.connection.close();
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});